Repository woohyun212/ASVS-korean, pull requests merged in 2025-07, with the labels that each got.

#15 0x11 in progress
  5.0/ko/0x11-V2-Validation-and-Business-Logic.md
  5.0/ko/0x13-V4-API-and-Web-Service.md
Labels: 리뷰, 병합 검토

#16 0x01 in progress
  5.0/ko/0x01-Frontispiece.md
Labels: 리뷰, 수정

#4 0x10 in progress
  5.0/ko/0x10-V1-Encoding-and-Sanitization.md
Labels: 리뷰, 수정

#13 0x21 in progress
  5.0/ko/0x21-V12-Secure-Communication.md
Labels: 리뷰, 수정

#41 0x18 in progress
  5.0/ko/0x18-V9-Self-contained-Tokens.md
Labels: 병합 검토
