Repository woohyun212/ASVS-korean, pull requests merged in 2025-08, with the labels that each got.

#14 0x04 in progress
  5.0/ko/0x04-Assessment_and_Certification.md
Labels: 수정

#63 0x91 in progress
  5.0/ko/0x91-Appendix-B_References.md
Labels: 병합 검토

#65 0x94 in progress
  5.0/ko/0x94-Appendix-E_Contributors.md
Labels: 병합 검토

#53 0x02 in progress
  5.0/ko/0x02-Preface.md
Labels: 병합 검토, 수정
